#!/usr/bin/env python3
"""Build the app's course data from source course files (data/courses/*.json).

Source files hold one lap as [distance m, elevation m, lat, lon] points plus provenance; see
data/courses/README.md. This writes src/courses/data/<id>.json (loaded when a course is picked)
and src/courses/catalog.ts (names, stats and a small profile preview for the course picker).

    python3 scripts/build-courses.py
"""
import json
import math
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / 'data' / 'courses'
OUT = ROOT / 'src' / 'courses'

# Official lap lengths, where the mapped route runs a little long or short.
OFFICIAL_LAP_M = {'richmond-2015': 16220}
# Points in the picker's little elevation profile.
PREVIEW_POINTS = 60


def climb(profile):
    return sum(max(0, b[1] - a[1]) for a, b in zip(profile, profile[1:]))


def max_grade(profile, span=50):
    """Steepest grade over `span` metres (what a rider feels), not a single 25 m step."""
    best = 0
    j = 0
    for i, (d, e) in enumerate(profile):
        while j < len(profile) - 1 and profile[j][0] < d + span:
            j += 1
        run = profile[j][0] - d
        if run >= span * 0.8:
            best = max(best, abs(profile[j][1] - e) / run)
    return best


def terrain(climb_m, lap_m):
    per_km = climb_m / (lap_m / 1000)
    return 'Flat' if per_km < 4 else 'Rolling' if per_km < 12 else 'Hilly'


def build(src):
    c = json.loads(src.read_text())
    pts = c['points']
    lap = pts[-1][0]
    k = OFFICIAL_LAP_M.get(c['id'], lap) / lap
    profile = [[round(p[0] * k), round(p[1], 1)] for p in pts]
    profile[-1][1] = profile[0][1]
    track = [[round(p[2], 5), round(p[3], 5)] for p in pts]
    lap_m = profile[-1][0]
    course = {
        'id': c['id'],
        'name': c['name'],
        'place': c['place'],
        'kind': c.get('kind', 'loop'),
        'lapMeters': lap_m,
        'profile': profile,
        'track': track,
        'climbs': [
            {**cl, 'start': round(cl['start'] * k), 'end': round(cl['end'] * k)} for cl in c.get('climbs', [])
        ],
        'source': c['source'],
    }
    (OUT / 'data' / f"{c['id']}.json").write_text(json.dumps(course, separators=(',', ':'), ensure_ascii=False))

    # Preview: elevation at evenly spaced points, for the picker's little profile.
    preview = []
    j = 0
    for i in range(PREVIEW_POINTS):
        d = lap_m * i / (PREVIEW_POINTS - 1)
        while j < len(profile) - 2 and profile[j + 1][0] < d:
            j += 1
        (d0, e0), (d1, e1) = profile[j], profile[j + 1]
        preview.append(round(e0 + (e1 - e0) * ((d - d0) / (d1 - d0) if d1 > d0 else 0), 1))
    up = climb(profile)
    return {
        'id': c['id'],
        'name': c['name'],
        'place': c['place'],
        'kind': course['kind'],
        'lapMeters': lap_m,
        'climbMeters': round(up),
        'maxGrade': round(max_grade(profile), 3),
        'altitudeM': round(sum(p[1] for p in profile) / len(profile)),
        'terrain': terrain(up, lap_m),
        'preview': preview,
    }


def main():
    (OUT / 'data').mkdir(parents=True, exist_ok=True)
    metas = [build(p) for p in sorted(SRC.glob('*.json'))]
    # Picker order: flattest first.
    order = {'Flat': 0, 'Rolling': 1, 'Hilly': 2}
    metas.sort(key=lambda m: (order[m['terrain']], m['climbMeters'] / m['lapMeters']))
    ts = (
        '// Generated by scripts/build-courses.py from data/courses/*.json. Do not edit.\n'
        "import type { CourseMeta } from './types';\n\n"
        '// prettier-ignore\n'
        f'export const CATALOG: CourseMeta[] = {json.dumps(metas, ensure_ascii=False, indent=2)};\n'
    )
    (OUT / 'catalog.ts').write_text(ts)
    for m in metas:
        print(f"{m['id']:18} {m['lapMeters']/1000:5.1f} km  {m['climbMeters']:4} m  max {m['maxGrade']*100:4.1f}%  {m['terrain']}  ~{m['altitudeM']} m asl")


if __name__ == '__main__':
    main()
